import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Game,defaultDeck} from '../engine.js';
const cards=JSON.parse(fs.readFileSync(new URL('../TCG Data/data/cards_master.json',import.meta.url))).cards;
const db=Object.fromEntries(cards.map(c=>[c.card_code,c]));
const make=()=>new Game(db,[defaultDeck(),defaultDeck()],{scenario:true,rng:()=>.5});
const card=(g,code)=>({code,uid:++g.serial,bonus:0});
const resolve=g=>{while(g.queue.length){g.activate(g.queue[0].id);if(g.choice)break;}};
test('Crownless mills the opponent for either owner',()=>{for(const i of [0,1]){const g=make(),n=g.players[1-i].deck.length,own=g.players[i].deck.length;g.turn=2;g.advantagePlayer=i;g.lastDamage={i:1-i,amount:2};g.actionEvent('damageDealt',i,card(g,'BP01-041'));resolve(g);assert.equal(g.players[1-i].deck.length,n-3);assert.equal(g.players[i].deck.length,own);}});
test('Crimson Pistil bonus requires two action cards and is applied once',()=>{for(const n of [1,2,3]){const g=make(),x=card(g,'BP01-050');g.players[0].action=[...Array.from({length:n-1},()=>card(g,'SD01-017')),x];g.actionEvent('combo',0,x);resolve(g);assert.equal(x.bonus,n>=2?1:0);}});
test('Rover M heavy attack costs a discard and gives exactly one optional bonus',()=>{const g=make(),x=card(g,'BP01-067');g.actionEvent('combo',0,x);assert.equal(x.bonus,0);assert.equal(g.queue[0].optional,true);g.activate(g.queue[0].id);assert.equal(x.bonus,0);const n=g.players[0].hand.length;g.answer([g.choice.items[0].uid]);assert.equal(g.players[0].hand.length,n-1);assert.equal(x.bonus,1);});
test('Whizzing Fight Spirit returns on loss to blue, not loss to red',()=>{for(const code of ['SD02-008','SD02-007']){const g=make(),x=card(g,'SD01-010');g.players[0].action=[x];g.selected=[x,card(g,code)];g.counterWinner=1;g.actionEvent('judgement',0,x);resolve(g);assert.equal(g.players[0].hand.includes(x),code==='SD02-008');}});
test('Camellya level zero does not retrieve Basic Attack on level up',()=>{const g=make(),x=card(g,'BP01-005'),basic=card(g,'BP01-044');g.players[0].trash.push(basic);g.enterSkill(0,x);assert.ok(g.players[0].trash.includes(basic));});
test('Camellya loss reveal requires own counter to be red',()=>{const g=make();g.players[0].chars[0]=[card(g,'BP01-004')];g.players[0].leader=0;g.selected=[card(g,'SD01-020'),card(g,'SD02-008')];g.counterWinner=1;g.charEvent('judgement',0);assert.equal(g.queue.length,0);});
test('each-turn Rover M draw requires Leader and works on enemy turn',()=>{for(const leader of [0,1]){const g=make();g.players[1].chars[0]=[card(g,'SD02-001')];g.players[1].leader=leader;const n=g.players[1].hand.length;g.endTurn();resolve(g);assert.equal(g.players[1].hand.length,n+(leader===0?1:0));}});
test('Sanhua end-turn resource requires Leader',()=>{for(const leader of [0,1]){const g=make();g.players[1].chars[0]=[card(g,'SD02-003')];g.players[1].leader=leader;const n=g.players[1].concerto.length;g.endTurn();resolve(g);assert.equal(g.players[1].concerto.length,n+(leader===0?1:0));}});
test('Counter-only Sanhua does not gain resources again at end',()=>{const g=make();g.players[0].chars[0]=[card(g,'BP01-033')];g.players[0].leader=0;const n=g.players[0].concerto.length;g.endTurn();assert.equal(g.players[0].concerto.length,n);});
test('Encore ability-only level two cannot be manually levelled',()=>{const g=make();g.players[0].chars[0]=[card(g,'BP01-013')];g.players[0].reserve.push(card(g,'BP01-011'));assert.equal(g.levelOptions(0,0).some(x=>x.code==='BP01-011'),false);});
